---
version: 1.6.4
name: Headset • Simple music player for YouTube
title: Headset Docs
description: Useful Resources
url: https://headsetapp.co
repository: https://github.com/headsetapp/headset-electron
twitter:
  username: headsetapp
exclude:
- ".gitignore"
- CNAME
- readme.md